#!/usr/bin/env python3
"""Regression checks for complete, classified exported diffs."""
from __future__ import annotations

import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PYTHON_RUNTIME = ROOT / "runtime" / "python"
if str(PYTHON_RUNTIME) not in sys.path:
    sys.path.insert(0, str(PYTHON_RUNTIME))

from bridge import smell_bridge


def _run(root: Path, *args: str) -> None:
    subprocess.run(
        list(args),
        cwd=root,
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )


def _write(root: Path, relative: str, value: str) -> None:
    path = root / relative
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(value, encoding="utf-8")


def main() -> None:
    with tempfile.TemporaryDirectory(prefix="snapshot-diff-hygiene-") as raw:
        root = Path(raw) / "rrdtool"
        root.mkdir()
        _run(root, "git", "init", "-q")
        _run(root, "git", "config", "user.email", "guard@example.invalid")
        _run(root, "git", "config", "user.name", "Guard Check")
        _write(root, "src/target.c", "int target(void) { return 1; }\n")
        _write(root, "tests/target_test.c", "int test_target(void) { return 1; }\n")
        _write(root, "qa/oracle.py", "expected = 1\n")
        _write(root, "spec/protocol.md", "not a test tree\n")
        _write(root, "Makefile", "all:\n\t@true\n")
        _write(root, "src/Makefile.inc", "CSOURCES = target.c\n")
        _write(root, "configure.ac", "AC_INIT([fixture], [1.0])\n")
        _write(root, "Makefile.am", "SUBDIRS = src sub\n")
        _write(root, "CMakeLists.txt", "project(fixture C)\n")
        _write(
            root,
            "cmake/CTestTestfile.cmake",
            "# project-owned test registration\nset(PROJECT_TESTS target)\n",
        )
        _write(root, "pkgconfig/project.pc", "Name: project\nVersion: 1\n")
        _write(root, "ci/project.ninja", "rule project_check\n  command = true\n")
        _write(root, "tools/configure", "#!/bin/sh\necho project-owned\n")
        _write(root, "build-aux/custom-check.sh", "#!/bin/sh\nexit 0\n")
        _write(root, "configure", "# generated by GNU Autoconf\nversion=1\n")
        _write(root, "aclocal.m4", "# generated automatically by aclocal\n")
        _write(root, "config.h.in", "/* generated by autoheader */\n")
        _write(
            root,
            "sub/Makefile.in",
            "# Makefile.in generated by automake from Makefile.am.\n",
        )
        _write(root, "sub/Makefile.am", "noinst_PROGRAMS = fixture\n")
        _write(root, "docs/note.md", "baseline\n")
        _write(root, "po/fr.po", "baseline translation\n")
        _write(root, "po/hu.po", "baseline translation\n")
        _write(root, "tests/graph2.output", "baseline generated output\n")
        _run(root, "git", "add", ".")
        _run(root, "git", "commit", "-qm", "baseline")
        baseline_commit = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=root,
            check=True,
            stdout=subprocess.PIPE,
            text=True,
        ).stdout.strip()

        _write(root, "src/target.c", "int target(void) { return 2; }\n")
        _write(root, "src/new.h", "int target(void);\n")
        _write(root, "src/new\nline.c", "int newline_path(void) { return 1; }\n")
        _write(root, "tests/target_test.c", "int test_target(void) { return 2; }\n")
        _write(root, "qa/oracle.py", "expected = 2\n")
        _write(root, "spec/protocol.md", "still not a test tree\n")
        _write(root, "Makefile", "all:\n\t@echo rebuilt\n")
        _write(root, "src/Makefile.inc", "CSOURCES = target.c new.c\n")
        _write(root, "configure.ac", "AC_INIT([fixture], [2.0])\n")
        _write(root, "Makefile.am", "SUBDIRS = src sub tools\n")
        _write(root, "CMakeLists.txt", "project(fixture C)\nadd_subdirectory(src)\n")
        _write(
            root,
            "cmake/CTestTestfile.cmake",
            "# project-owned test registration\nset(PROJECT_TESTS target extra)\n",
        )
        _write(root, "pkgconfig/project.pc", "Name: project\nVersion: 2\n")
        _write(
            root,
            "ci/project.ninja",
            "rule project_check\n  command = ./project-check\n",
        )
        _write(root, "cmake/new-module.cmake", "set(PROJECT_FEATURE ON)\n")
        _write(root, "pkgconfig/new.pc", "Name: project-extra\nVersion: 1\n")
        _write(root, "ci/new.ninja", "rule project_extra\n  command = true\n")
        _write(root, "tools/configure", "#!/bin/sh\necho project-change\n")
        _write(root, "build-aux/custom-check.sh", "#!/bin/sh\nexit 2\n")
        _write(root, "build/real_source.c", "int build_api(void) { return 1; }\n")
        _write(root, "docs/note.md", "changed\n")
        _write(root, "po/fr.po", "msgmerge regenerated translation\n")
        _write(root, "po/hu.po", "msgmerge regenerated translation\n")
        _write(root, "tests/graph2.output", "test regenerated output\n")
        # These are prior focused-verification products, not deliverables.
        _write(root, "configure", "# generated by GNU Autoconf\nversion=2\n")
        _write(root, "aclocal.m4", "# regenerated automatically by aclocal\n")
        _write(root, "config.h.in", "/* regenerated by autoheader */\n")
        _write(
            root,
            "sub/Makefile.in",
            "# Makefile.in generated by automake from Makefile.am.\nregen = 1\n",
        )
        _write(root, "config.status", "# generated by configure\n")
        _write(
            root,
            "sub/Makefile",
            "# Makefile.  Generated from Makefile.in by configure.\n",
        )
        _write(root, "autom4te.cache/traces.0", "generated trace\n")
        _write(root, "build-aux/compile", "#!/bin/sh\n# automake helper\n")
        _write(
            root,
            ".smell-test-reports/TEST-focused.xml",
            '<testsuite tests="1" failures="0"/>\n',
        )
        _write(
            root,
            "build-refactoragent/generated.cc",
            "int generated(void) { return 2; }\n",
        )
        _write(
            root,
            "CMakeCache.txt",
            "# This is the CMakeCache file.\nCMAKE_GENERATOR:INTERNAL=Ninja\n",
        )
        _write(
            root,
            "generated/CTestTestfile.cmake",
            "# CMake generated Testfile for source directory fixture\n",
        )
        _write(
            root,
            "build.ninja",
            "# CMAKE generated file: DO NOT EDIT!\n"
            "# Generated by \"Ninja\" Generator, CMake Version 3.31\n",
        )
        _write(
            root,
            "manual/CMakeCache.txt",
            "# project-owned cache seed, not a generated cache\nPROJECT_MODE=1\n",
        )
        _write(
            root,
            "manual-tree/CMakeFiles/project.cmake",
            "# project-owned CMake module in a unfortunately named directory\n",
        )
        _write(
            root,
            "manual-tree/Testing/baseline.output",
            "project-owned test baseline\n",
        )

        # Staged edits must not disappear from the exported patch.
        _run(root, "git", "add", "Makefile")
        _run(root, "git", "config", "diff.mnemonicPrefix", "true")
        _run(root, "git", "config", "diff.algorithm", "histogram")
        _run(root, "git", "config", "diff.indentHeuristic", "true")
        snapshot = smell_bridge._snapshot_project(
            root,
            declared_test_paths=["qa/oracle.py"],
            base_commit=baseline_commit,
        )
        patch = snapshot["diff"]["stdout"]
        stat = snapshot["diff_stat"]["stdout"]
        status = snapshot["status"]["stdout"]
        assert snapshot["scope"] == "full_worktree_pre_verification"
        for rendered in (patch, stat, status):
            assert "src/target.c" in rendered, rendered
            assert "build-refactoragent" not in rendered, rendered
            assert ".smell-test-reports" not in rendered, rendered
            assert "autom4te.cache" not in rendered, rendered
            assert "config.status" not in rendered, rendered
            assert "po/fr.po" in rendered, rendered
            assert "po/hu.po" in rendered, rendered
            assert "tests/graph2.output" in rendered, rendered
            assert "cmake/CTestTestfile.cmake" in rendered, rendered
            assert "pkgconfig/project.pc" in rendered, rendered
            assert "ci/project.ninja" in rendered, rendered
            assert "cmake/new-module.cmake" in rendered, rendered
            assert "pkgconfig/new.pc" in rendered, rendered
            assert "ci/new.ninja" in rendered, rendered
            assert "manual/CMakeCache.txt" in rendered, rendered
            assert "manual-tree/CMakeFiles/project.cmake" in rendered, rendered
            assert "manual-tree/Testing/baseline.output" in rendered, rendered
            assert "generated/CTestTestfile.cmake" not in rendered, rendered
            assert "CMakeCache.txt" not in rendered.replace(
                "manual/CMakeCache.txt", ""
            ), rendered
            assert "build.ninja" not in rendered, rendered
        assert "src/new.h" in patch, patch
        assert "build/real_source.c" in patch, patch
        assert "tests/target_test.c" in patch, patch
        assert "qa/oracle.py" in patch, patch
        assert "Makefile" in patch, patch
        assert "configure.ac" in patch, patch
        assert "Makefile.am" in patch, patch
        assert "CMakeLists.txt" in patch, patch
        assert "tools/configure" in patch, patch
        assert "build-aux/custom-check.sh" in patch, patch
        assert "docs/note.md" in patch, patch
        for tracked_generated in (
            "configure",
            "aclocal.m4",
            "config.h.in",
            "sub/Makefile.in",
        ):
            assert any(
                item["path"] == tracked_generated
                and item["category"] == "build_metadata"
                for item in snapshot["change_audit"]["changes"]
            ), (tracked_generated, snapshot["change_audit"])
        for untracked_generated in (
            "sub/Makefile",
            "build-aux/compile",
            "CMakeCache.txt",
            "generated/CTestTestfile.cmake",
            "build.ninja",
        ):
            assert not any(
                item["path"] == untracked_generated
                for item in snapshot["change_audit"]["changes"]
            ), (untracked_generated, snapshot["change_audit"])
        assert "--- a/src/target.c" in patch, patch
        assert "+++ b/src/target.c" in patch, patch

        audit = snapshot["change_audit"]
        assert audit["success"] is True, audit
        assert audit["category_counts"] == {
            "production": 4,
            "test": 4,
            "build_metadata": 19,
            "other": 4,
        }, audit
        assert any(
            item["path"] == "src/Makefile.inc"
            and item["category"] == "build_metadata"
            for item in audit["changes"]
        ), audit
        assert any(
            item["path"] == "src/new\nline.c"
            for item in audit["changes"]
        ), audit
        assert audit["ignored_tracked_count"] == 0, audit
        assert audit["ignored_untracked_count"] == 9, audit
        assert audit["ignored_generated_count"] == 9, audit
        assert snapshot["status"]["ignored_tracked_count"] == 0, snapshot["status"]
        assert snapshot["status"]["ignored_untracked_count"] == 9, snapshot["status"]

        immutable = smell_bridge._worktree_test_change_audit(
            audit,
            allow_test_changes=False,
        )
        assert immutable["success"] is False, immutable
        assert immutable["status"] == "TEST_SOURCE_MODIFIED", immutable
        assert immutable["added"] == [
            {"path": "manual-tree/Testing/baseline.output"},
        ], immutable
        assert immutable["changed"] == [
            {"path": "qa/oracle.py"},
            {"path": "tests/graph2.output"},
            {"path": "tests/target_test.c"},
        ], immutable

        allowed = smell_bridge._worktree_test_change_audit(
            audit,
            allow_test_changes=True,
        )
        assert allowed["success"] is True, allowed
        assert allowed["status"] == "TEST_SOURCE_CHANGE_ALLOWED", allowed

        # A candidate-created commit must not erase the c000-relative delivery
        # patch or hide its test edits. Commit only the deliverable paths; the
        # generated build tree remains an ignored untracked artifact.
        _run(
            root,
            "git", "add",
            "src", "tests", "qa", "spec", "Makefile", "docs",
            "src/Makefile.inc", "configure.ac", "Makefile.am",
            "CMakeLists.txt", "tools/configure", "build/real_source.c",
            "build-aux/custom-check.sh",
        )
        _run(root, "git", "commit", "-qm", "candidate commit")
        committed_snapshot = smell_bridge._snapshot_project(
            root,
            declared_test_paths=["qa/oracle.py"],
            base_commit=baseline_commit,
        )
        committed_patch = committed_snapshot["diff"]["stdout"]
        committed_audit = committed_snapshot["change_audit"]
        assert committed_snapshot["base_commit"] == baseline_commit
        assert "src/target.c" in committed_patch, committed_patch
        assert "tests/target_test.c" in committed_patch, committed_patch
        assert "Makefile" in committed_patch, committed_patch
        assert committed_audit["category_counts"] == audit["category_counts"], (
            committed_audit,
            audit,
        )
        committed_immutable = smell_bridge._worktree_test_change_audit(
            committed_audit,
            allow_test_changes=False,
        )
        assert committed_immutable["status"] == "TEST_SOURCE_MODIFIED", (
            committed_immutable
        )

    print(
        "snapshot diff hygiene self-check passed: "
        "c000-relative committed/staged/unstaged patch; "
        "provenance-marked untracked verification products excluded; "
        "tracked and source-owned build/test metadata retained; "
        "production/test/build metadata classified; "
        "immutable test edits fail closed"
    )


if __name__ == "__main__":
    main()
