#!/usr/bin/env python3
"""Regression checks for complete, classified exported diffs."""
from __future__ import annotations

import os
import subprocess
import sys
import tempfile
from pathlib import Path
from types import SimpleNamespace

ROOT = Path(__file__).resolve().parents[1]
PYTHON_RUNTIME = ROOT / "runtime" / "python"
if str(PYTHON_RUNTIME) not in sys.path:
    sys.path.insert(0, str(PYTHON_RUNTIME))

from bridge import smell_bridge


def _run(root: Path, *args: str) -> None:
    subprocess.run(
        list(args),
        cwd=root,
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )


def _write(root: Path, relative: str, value: str) -> None:
    path = root / relative
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(value, encoding="utf-8")


def _write_bytes(root: Path, relative: str, value: bytes) -> None:
    path = root / relative
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(value)


def main() -> None:
    with tempfile.TemporaryDirectory(prefix="snapshot-diff-hygiene-") as raw:
        root = Path(raw) / "fixture-project"
        root.mkdir()
        _run(root, "git", "init", "-q")
        _run(root, "git", "config", "user.email", "guard@example.invalid")
        _run(root, "git", "config", "user.name", "Guard Check")
        _write(root, "src/target.c", "int target(void) { return 1; }\n")
        _write(root, "tests/target_test.c", "int test_target(void) { return 1; }\n")
        _write(root, "qa/oracle.py", "expected = 1\n")
        _write(root, "spec/protocol.md", "not a test tree\n")
        _write(root, "Makefile", "all:\n\t@true\n")
        _write(root, "src/Makefile.inc", "CSOURCES = target.c\n")
        _write(root, "configure.ac", "AC_INIT([fixture], [1.0])\n")
        _write(root, "Makefile.am", "SUBDIRS = src sub\n")
        _write(root, "CMakeLists.txt", "project(fixture C)\n")
        _write(
            root,
            "cmake/CTestTestfile.cmake",
            "# project-owned test registration\nset(PROJECT_TESTS target)\n",
        )
        _write(root, "pkgconfig/project.pc", "Name: project\nVersion: 1\n")
        _write(root, "ci/project.ninja", "rule project_check\n  command = true\n")
        _write(root, "tools/configure", "#!/bin/sh\necho project-owned\n")
        _write(root, "build-aux/custom-check.sh", "#!/bin/sh\nexit 0\n")
        _write(root, "configure", "# generated by GNU Autoconf\nversion=1\n")
        _write(root, "aclocal.m4", "# generated automatically by aclocal\n")
        _write(root, "config.h.in", "/* generated by autoheader */\n")
        _write(
            root,
            "sub/Makefile.in",
            "# Makefile.in generated by automake from Makefile.am.\n",
        )
        _write(root, "sub/Makefile.am", "noinst_PROGRAMS = fixture\n")
        _write(root, "docs/note.md", "baseline\n")
        _write(root, "po/fr.po", "baseline translation\n")
        _write(root, "po/hu.po", "baseline translation\n")
        _write(root, "tests/graph2.output", "baseline generated output\n")
        _write(
            root,
            "build-refactoragent/tracked-generated.cc",
            "int tracked_generated(void) { return 1; }\n",
        )
        _write(root, "build-refactoragent/removed-generated.o", "old object\n")
        _write(
            root,
            ".smell-test-reports/TEST-tracked.xml",
            '<testsuite tests="1" failures="0"/>\n',
        )
        _write(
            root,
            ".smell-test-reports/TEST-removed.xml",
            '<testsuite tests="1" failures="0"/>\n',
        )
        _run(root, "git", "add", ".")
        _run(root, "git", "commit", "-qm", "baseline")
        baseline_commit = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=root,
            check=True,
            stdout=subprocess.PIPE,
            text=True,
        ).stdout.strip()

        _write(root, "src/target.c", "int target(void) { return 2; }\n")
        _write(root, "src/new.h", "int target(void);\n")
        _write(root, "src/new\nline.c", "int newline_path(void) { return 1; }\n")
        _write(root, "tests/target_test.c", "int test_target(void) { return 2; }\n")
        _write(root, "qa/oracle.py", "expected = 2\n")
        _write(root, "spec/protocol.md", "still not a test tree\n")
        _write(root, "Makefile", "all:\n\t@echo rebuilt\n")
        _write(root, "src/Makefile.inc", "CSOURCES = target.c new.c\n")
        _write(root, "configure.ac", "AC_INIT([fixture], [2.0])\n")
        _write(root, "Makefile.am", "SUBDIRS = src sub tools\n")
        _write(root, "CMakeLists.txt", "project(fixture C)\nadd_subdirectory(src)\n")
        _write(
            root,
            "cmake/CTestTestfile.cmake",
            "# project-owned test registration\nset(PROJECT_TESTS target extra)\n",
        )
        _write(root, "pkgconfig/project.pc", "Name: project\nVersion: 2\n")
        _write(
            root,
            "ci/project.ninja",
            "rule project_check\n  command = ./project-check\n",
        )
        _write(root, "cmake/new-module.cmake", "set(PROJECT_FEATURE ON)\n")
        _write(root, "pkgconfig/new.pc", "Name: project-extra\nVersion: 1\n")
        _write(root, "ci/new.ninja", "rule project_extra\n  command = true\n")
        _write(root, "tools/configure", "#!/bin/sh\necho project-change\n")
        _write(root, "build-aux/custom-check.sh", "#!/bin/sh\nexit 2\n")
        _write(root, "build/real_source.c", "int build_api(void) { return 1; }\n")
        _write(root, "docs/note.md", "changed\n")
        _write(root, "po/fr.po", "msgmerge regenerated translation\n")
        _write(root, "po/hu.po", "msgmerge regenerated translation\n")
        _write(root, "tests/graph2.output", "test regenerated output\n")
        _write(
            root,
            "build-refactoragent/tracked-generated.cc",
            "int tracked_generated(void) { return 2; }\n",
        )
        (root / "build-refactoragent/removed-generated.o").unlink()
        _write(
            root,
            "build-refactoragent/added-generated.ninja",
            "rule generated\n  command = true\n",
        )
        _write(
            root,
            ".smell-test-reports/TEST-tracked.xml",
            '<testsuite tests="2" failures="0"/>\n',
        )
        (root / ".smell-test-reports/TEST-removed.xml").unlink()
        _write(
            root,
            ".smell-test-reports/TEST-added.xml",
            '<testsuite tests="2" failures="0"/>\n',
        )
        # These are prior focused-verification products, not deliverables.
        # A candidate must not evade the frozen generated-file contract by
        # deleting the generator marker from an already-generated tracked file.
        _write(root, "configure", "#!/bin/sh\nversion=2\n")
        _write(root, "aclocal.m4", "# regenerated automatically by aclocal\n")
        _write(root, "config.h.in", "/* regenerated by autoheader */\n")
        (root / "sub/Makefile.in").unlink()
        _write(root, "config.status", "# generated by configure\n")
        _write(
            root,
            "sub/Makefile",
            "# Makefile.  Generated from Makefile.in by configure.\n",
        )
        _write(root, "autom4te.cache/traces.0", "generated trace\n")
        _write(root, "build-aux/compile", "#!/bin/sh\n# automake helper\n")
        _write(
            root,
            ".smell-test-reports/TEST-focused.xml",
            '<testsuite tests="1" failures="0"/>\n',
        )
        _write(
            root,
            "build-refactoragent/generated.cc",
            "int generated(void) { return 2; }\n",
        )
        _write(root, ".opencode/controller.json", '{"owned": true}\n')
        _write(root, ".smell-artifacts/verify/evidence.json", "{}\n")
        _write(root, ".idea-refactoring/session.json", "{}\n")
        _write(root, ".idea/workspace.xml", "<project/>\n")
        _write(root, "opencode.json", '{"controller": true}\n')
        _write(root, "docs/.opencode/note.md", "project-owned nested path\n")
        _write(
            root,
            "CMakeCache.txt",
            "# This is the CMakeCache file.\nCMAKE_GENERATOR:INTERNAL=Ninja\n",
        )
        _write(
            root,
            "generated/CTestTestfile.cmake",
            "# CMake generated Testfile for source directory fixture\n",
        )
        _write(
            root,
            "build.ninja",
            "# CMAKE generated file: DO NOT EDIT!\n"
            "# Generated by \"Ninja\" Generator, CMake Version 3.31\n",
        )
        _write(
            root,
            "manual/CMakeCache.txt",
            "# project-owned cache seed, not a generated cache\nPROJECT_MODE=1\n",
        )
        _write(
            root,
            "manual-tree/CMakeFiles/project.cmake",
            "# project-owned CMake module in a unfortunately named directory\n",
        )
        _write(
            root,
            "manual-tree/Testing/baseline.output",
            "project-owned test baseline\n",
        )
        # Root-level compiled products must remain visible in the exported
        # diff, but they are never an acceptable deliverable.
        generated_files = ("combined.o", "support.o", "fixture_test")
        for generated_path in generated_files:
            _write_bytes(
                root,
                generated_path,
                b"\x7fELF\x02\x01\x01\x00generated-build-product",
            )
        _write_bytes(root, "libfixture.a", b"!<arch>\ngenerated-archive")
        _write_bytes(
            root,
            "libfixture.so.1.0.0",
            b"\x7fELF\x02\x01\x01\x00generated-shared-library",
        )
        (root / "libfixture.so.1").symlink_to("libfixture.so.1.0.0")
        (root / "libfixture.so").symlink_to("libfixture.so.1")
        generated_root_products = (
            *generated_files,
            "libfixture.a",
            "libfixture.so.1.0.0",
            "libfixture.so.1",
            "libfixture.so",
        )

        # Staged edits must not disappear from the exported patch.
        _run(
            root,
            "git",
            "add",
            "Makefile",
            "build-refactoragent/added-generated.ninja",
            ".smell-test-reports/TEST-added.xml",
        )
        _run(root, "git", "config", "diff.mnemonicPrefix", "true")
        _run(root, "git", "config", "diff.algorithm", "histogram")
        _run(root, "git", "config", "diff.indentHeuristic", "true")
        original_git_diff_with_untracked = smell_bridge._git_diff_with_untracked
        replay_diff_calls: list[bool] = []

        def _unexpected_replay_diff(*_args, **_kwargs):
            replay_diff_calls.append(True)
            raise AssertionError(
                "artifact-polluted snapshots must not serialize replay diffs"
            )

        try:
            smell_bridge._git_diff_with_untracked = _unexpected_replay_diff
            snapshot = smell_bridge._snapshot_project(
                root,
                declared_test_paths=["qa/oracle.py"],
                base_commit=baseline_commit,
            )
        finally:
            smell_bridge._git_diff_with_untracked = original_git_diff_with_untracked
        assert replay_diff_calls == [], replay_diff_calls
        patch = snapshot["diff"]["stdout"]
        stat = snapshot["diff_stat"]["stdout"]
        status = snapshot["status"]["stdout"]
        assert snapshot["scope"] == "full_worktree_pre_verification"
        assert patch == "" and stat == "", snapshot
        for skipped in (snapshot["diff"], snapshot["diff_stat"]):
            assert skipped["returncode"] != 0, skipped
            assert skipped["skipped"] is True, skipped
            assert skipped["skipped_reason"] == (
                "FINAL_DIFF_GENERATED_ARTIFACTS"
            ), skipped
        for rendered in (status,):
            assert "src/target.c" in rendered, rendered
            assert "build-refactoragent/tracked-generated.cc" in rendered, rendered
            assert "build-refactoragent/removed-generated.o" in rendered, rendered
            assert "build-refactoragent/added-generated.ninja" in rendered, rendered
            assert ".smell-test-reports/TEST-tracked.xml" in rendered, rendered
            assert ".smell-test-reports/TEST-removed.xml" in rendered, rendered
            assert ".smell-test-reports/TEST-added.xml" in rendered, rendered
            assert "build-refactoragent/generated.cc" in rendered, rendered
            assert ".smell-test-reports/TEST-focused.xml" in rendered, rendered
            assert "autom4te.cache" in rendered, rendered
            assert "config.status" in rendered, rendered
            assert ".opencode/controller.json" not in rendered, rendered
            assert ".smell-artifacts/verify/evidence.json" not in rendered, rendered
            assert ".idea-refactoring/session.json" not in rendered, rendered
            assert ".idea/workspace.xml" not in rendered, rendered
            assert "opencode.json" not in rendered, rendered
            assert "docs/.opencode/note.md" in rendered, rendered
            assert "po/fr.po" in rendered, rendered
            assert "po/hu.po" in rendered, rendered
            assert "tests/graph2.output" in rendered, rendered
            assert "cmake/CTestTestfile.cmake" in rendered, rendered
            assert "pkgconfig/project.pc" in rendered, rendered
            assert "ci/project.ninja" in rendered, rendered
            assert "cmake/new-module.cmake" in rendered, rendered
            assert "pkgconfig/new.pc" in rendered, rendered
            assert "ci/new.ninja" in rendered, rendered
            assert "manual/CMakeCache.txt" in rendered, rendered
            assert "manual-tree/CMakeFiles/project.cmake" in rendered, rendered
            assert "manual-tree/Testing/baseline.output" in rendered, rendered
            assert "generated/CTestTestfile.cmake" in rendered, rendered
            assert "CMakeCache.txt" in rendered.replace(
                "manual/CMakeCache.txt", ""
            ), rendered
            assert "build.ninja" in rendered, rendered
            for generated_path in generated_root_products:
                assert generated_path in rendered, (generated_path, rendered)
        assert "src/new.h" in status, status
        assert "build/real_source.c" in status, status
        assert "tests/target_test.c" in status, status
        assert "qa/oracle.py" in status, status
        assert "Makefile" in status, status
        assert "configure.ac" in status, status
        assert "Makefile.am" in status, status
        assert "CMakeLists.txt" in status, status
        assert "tools/configure" in status, status
        assert "build-aux/custom-check.sh" in status, status
        assert "docs/note.md" in status, status
        for tracked_generated in (
            "configure",
            "aclocal.m4",
            "config.h.in",
            "sub/Makefile.in",
        ):
            assert any(
                item["path"] == tracked_generated
                and item["category"] == "build_metadata"
                for item in snapshot["change_audit"]["changes"]
            ), (tracked_generated, snapshot["change_audit"])
        for untracked_generated in (
            "sub/Makefile",
            "build-aux/compile",
            "CMakeCache.txt",
            "generated/CTestTestfile.cmake",
            "build.ninja",
        ):
            assert any(
                item["path"] == untracked_generated
                for item in snapshot["change_audit"]["changes"]
            ), (untracked_generated, snapshot["change_audit"])
        audit = snapshot["change_audit"]
        assert audit["success"] is True, audit
        final_artifacts = audit["final_diff_generated_artifact_audit"]
        assert final_artifacts["success"] is False, final_artifacts
        assert final_artifacts["status"] == (
            "FINAL_DIFF_GENERATED_ARTIFACTS"
        ), final_artifacts
        controller_owned_products = (
            "build-refactoragent/tracked-generated.cc",
            "build-refactoragent/removed-generated.o",
            "build-refactoragent/added-generated.ninja",
            "build-refactoragent/generated.cc",
            ".smell-test-reports/TEST-tracked.xml",
            ".smell-test-reports/TEST-removed.xml",
            ".smell-test-reports/TEST-added.xml",
            ".smell-test-reports/TEST-focused.xml",
        )
        tracked_autotools_products = (
            "configure",
            "aclocal.m4",
            "config.h.in",
            "sub/Makefile.in",
        )
        untracked_generated_products = (
            "CMakeCache.txt",
            "autom4te.cache/traces.0",
            "build-aux/compile",
            "build.ninja",
            "config.status",
            "generated/CTestTestfile.cmake",
            "sub/Makefile",
        )
        assert final_artifacts["paths"] == sorted(
            (
                *generated_root_products,
                *controller_owned_products,
                *tracked_autotools_products,
                *untracked_generated_products,
            )
        ), final_artifacts
        assert {
            item["path"]: item["operation"]
            for item in final_artifacts["artifacts"]
            if item["path"] in controller_owned_products
        } == {
            "build-refactoragent/tracked-generated.cc": "changed",
            "build-refactoragent/removed-generated.o": "deleted",
            "build-refactoragent/added-generated.ninja": "added",
            "build-refactoragent/generated.cc": "added",
            ".smell-test-reports/TEST-tracked.xml": "changed",
            ".smell-test-reports/TEST-removed.xml": "deleted",
            ".smell-test-reports/TEST-added.xml": "added",
            ".smell-test-reports/TEST-focused.xml": "added",
        }, final_artifacts
        assert "src/new.h" not in final_artifacts["paths"], final_artifacts
        assert "docs/note.md" not in final_artifacts["paths"], final_artifacts
        legal_delivery = smell_bridge._final_diff_generated_artifact_audit({
            "success": True,
            "changes": [
                {"path": "src/new.h", "operation": "added"},
                {"path": "docs/note.md", "operation": "added"},
                {"path": "src/libfixture.so", "operation": "added"},
                {"path": "libwidget.so", "operation": "added"},
                {"path": "unrelated.o", "operation": "added"},
                {"path": ".fixture.o", "operation": "added"},
                {
                    "path": "src/build-refactoragent/generated.cc",
                    "operation": "added",
                },
                {
                    "path": "docs/.smell-test-reports/note.md",
                    "operation": "changed",
                },
                {"path": "configure.ac", "operation": "changed"},
                {"path": "Makefile.am", "operation": "changed"},
                {"path": "CMakeLists.txt", "operation": "changed"},
                {"path": "tools/configure", "operation": "changed"},
                {
                    "path": "manual-tree/Testing/baseline.output",
                    "operation": "changed",
                },
            ],
        })
        assert legal_delivery["success"] is True, legal_delivery
        assert legal_delivery["status"] == (
            "FINAL_DIFF_GENERATED_ARTIFACTS_ABSENT"
        ), legal_delivery
        assert legal_delivery["paths"] == [], legal_delivery
        manual_baseline = smell_bridge._final_diff_generated_artifact_audit(
            {
                "success": True,
                "changes": [
                    {"path": "tests/graph2.output", "operation": "changed"},
                    {
                        "path": "tests/hand-authored.output",
                        "operation": "changed",
                    },
                ],
            },
            project_root=root,
        )
        assert manual_baseline["success"] is True, manual_baseline
        assert manual_baseline["paths"] == [], manual_baseline

        # Build-tree detection is based on generator provenance and content,
        # never on a project's name or a conventional build-directory name.
        generic_root = Path(raw) / "generic-project"
        generic_root.mkdir()
        _run(generic_root, "git", "init", "-q")
        _run(generic_root, "git", "config", "user.email", "guard@example.invalid")
        _run(generic_root, "git", "config", "user.name", "Guard Check")
        _write(generic_root, "src/existing.c", "int existing(void) { return 1; }\n")
        _write(generic_root, "CMakeLists.txt", "project(generic C)\n")
        _write(generic_root, "Makefile", "all:\n\t@true\n")
        _write(
            generic_root,
            ".gitignore",
            "ignored-arbitrary-output/\nnode_modules/\nignored-root-tool\n",
        )
        _run(generic_root, "git", "add", ".")
        _run(generic_root, "git", "commit", "-qm", "baseline")
        generic_baseline = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=generic_root,
            check=True,
            stdout=subprocess.PIPE,
            text=True,
        ).stdout.strip()

        _write(generic_root, "src/new.c", "int added(void) { return 2; }\n")
        _write(
            generic_root,
            "CMakeLists.txt",
            "project(generic C)\nadd_library(generic src/new.c)\n",
        )
        _write(generic_root, "Makefile", "all:\n\t@echo authored\n")
        _write(
            generic_root,
            "manual/CMakeCache.txt",
            "# hand-authored cache example\nPROJECT_MODE=1\n",
        )
        _write(
            generic_root,
            "manual-tree/CMakeFiles/project.cmake",
            "# hand-authored module\n",
        )
        _write(
            generic_root,
            "ci/project.ninja",
            "rule authored\n  command = true\n",
        )
        _write(generic_root, "unrelated.o", "hand-authored fixture\n")
        _write(
            generic_root,
            "src/marker_comment.c",
            "/* Documentation quotes: # This file is generated by cmake */\n"
            "int marker_comment(void) { return 1; }\n",
        )
        _write(
            generic_root,
            "src/marker_sibling.c",
            "int marker_sibling(void) { return 1; }\n",
        )

        _write(
            generic_root,
            "build-test/CMakeCache.txt",
            "# This is the CMakeCache file.\nCMAKE_GENERATOR:INTERNAL=Ninja\n",
        )
        _write(
            generic_root,
            "build-test/CMakeFiles/generic.dir/link.txt",
            "/usr/bin/cc generic.o -o generic\n",
        )
        _write_bytes(
            generic_root,
            "build-test/CMakeFiles/generic.dir/generic.o",
            b"\x7fELF\x02\x01\x01\x00generated-object",
        )
        _write(
            generic_root,
            "build_test/build.ninja",
            "# CMAKE generated file: DO NOT EDIT!\n"
            "# Generated by \"Ninja\" Generator, CMake Version 3.31\n",
        )
        _write(generic_root, "build_test/generated.cc", "int generated;\n")
        _write(
            generic_root,
            "out-uuid/rules.ninja",
            "# CMAKE generated file: DO NOT EDIT!\n",
        )
        _write_bytes(
            generic_root,
            "out-uuid/bin/generic-tool",
            b"\x7fELF\x02\x01\x01\x00generated-executable",
        )
        _write_bytes(
            generic_root,
            "combined.o",
            b"\x7fELF\x02\x01\x01\x00root-object",
        )
        _write_bytes(
            generic_root,
            "standalone-tool",
            b"\x7fELF\x02\x01\x01\x00root-executable",
        )
        _write(
            generic_root,
            "ignored-arbitrary-output/CMakeCache.txt",
            "# This is the CMakeCache file.\nCMAKE_GENERATOR:INTERNAL=Ninja\n",
        )
        _write(
            generic_root,
            "ignored-arbitrary-output/generated.cc",
            "int ignored_generated;\n",
        )
        _write_bytes(
            generic_root,
            "ignored-root-tool",
            b"\x7fELF\x02\x01\x01\x00ignored-root-executable",
        )
        _write(
            generic_root,
            "node_modules/package/cache.js",
            "module.exports = 'ordinary ignored dependency cache';\n",
        )

        generic_snapshot = smell_bridge._snapshot_project(
            generic_root,
            base_commit=generic_baseline,
        )
        generic_audit = generic_snapshot["change_audit"]
        generic_artifacts = generic_audit[
            "final_diff_generated_artifact_audit"
        ]
        expected_generic_artifacts = sorted((
            "build-test/CMakeCache.txt",
            "build-test/CMakeFiles/generic.dir/generic.o",
            "build-test/CMakeFiles/generic.dir/link.txt",
            "build_test/build.ninja",
            "build_test/generated.cc",
            "out-uuid/bin/generic-tool",
            "out-uuid/rules.ninja",
            "combined.o",
            "standalone-tool",
            "ignored-arbitrary-output/CMakeCache.txt",
            "ignored-root-tool",
        ))
        assert generic_artifacts["status"] == (
            "FINAL_DIFF_GENERATED_ARTIFACTS"
        ), generic_artifacts
        assert generic_artifacts["paths"] == expected_generic_artifacts, (
            generic_artifacts
        )
        assert generic_artifacts["derived_build_roots"] == [
            {
                "path": "build-test",
                "evidence_paths": ["build-test/CMakeCache.txt"],
            },
            {
                "path": "build_test",
                "evidence_paths": ["build_test/build.ninja"],
            },
            {
                "path": "ignored-arbitrary-output",
                "evidence_paths": [
                    "ignored-arbitrary-output/CMakeCache.txt"
                ],
            },
            {
                "path": "out-uuid",
                "evidence_paths": ["out-uuid/rules.ninja"],
            },
        ], generic_artifacts
        generic_evidence = {
            item["path"]: item["evidence"]
            for item in generic_artifacts["artifacts"]
        }
        assert generic_evidence["combined.o"] == "compiled-content:elf", (
            generic_evidence
        )
        assert generic_evidence["standalone-tool"] == "compiled-content:elf", (
            generic_evidence
        )
        assert generic_evidence["ignored-root-tool"] == (
            "compiled-content:elf"
        ), generic_evidence
        assert generic_evidence["build_test/generated.cc"] == (
            "generated-build-root"
        ), generic_evidence
        inventoried_paths = {
            item["path"] for item in generic_audit["changes"]
        }
        assert set(expected_generic_artifacts) <= inventoried_paths, generic_audit
        assert not any(
            path.startswith("node_modules/") for path in inventoried_paths
        ), generic_audit
        assert "ignored-arbitrary-output/generated.cc" not in inventoried_paths, (
            generic_audit
        )
        for rendered in (generic_snapshot["status"]["stdout"],):
            for artifact_path in expected_generic_artifacts:
                assert artifact_path in rendered, (artifact_path, rendered)
        for skipped in (
            generic_snapshot["diff_stat"],
            generic_snapshot["diff"],
        ):
            assert skipped["skipped_reason"] == (
                "FINAL_DIFF_GENERATED_ARTIFACTS"
            ), skipped
        for legal_path in (
            "src/new.c",
            "CMakeLists.txt",
            "Makefile",
            "manual/CMakeCache.txt",
            "manual-tree/CMakeFiles/project.cmake",
            "ci/project.ninja",
            "unrelated.o",
            "src/marker_comment.c",
            "src/marker_sibling.c",
        ):
            assert legal_path in inventoried_paths, (legal_path, generic_audit)
            assert legal_path not in generic_artifacts["paths"], (
                legal_path,
                generic_artifacts,
            )

        for legal_path in (
            "configure.ac",
            "Makefile.am",
            "CMakeLists.txt",
            "tools/configure",
            "docs/.opencode/note.md",
            "manual-tree/Testing/baseline.output",
        ):
            assert legal_path not in final_artifacts["paths"], final_artifacts
        assert audit["category_counts"] == {
            "production": 6,
            "test": 4,
            "build_metadata": 26,
            "other": 18,
        }, audit
        assert audit["ignored_tracked_count"] == 0, audit
        assert any(
            item["path"] == "src/Makefile.inc"
            and item["category"] == "build_metadata"
            for item in audit["changes"]
        ), audit
        assert any(
            item["path"] == "src/new\nline.c"
            for item in audit["changes"]
        ), audit
        assert audit["ignored_tracked_count"] == 0, audit
        assert audit["ignored_untracked_count"] == 5, audit
        assert audit["ignored_generated_count"] == 5, audit
        assert snapshot["status"]["ignored_tracked_count"] == 0, snapshot["status"]
        assert snapshot["status"]["ignored_untracked_count"] == 5, snapshot["status"]

        immutable = smell_bridge._worktree_test_change_audit(
            audit,
            allow_test_changes=False,
        )
        assert immutable["success"] is False, immutable
        assert immutable["status"] == "TEST_SOURCE_MODIFIED", immutable
        assert immutable["added"] == [
            {"path": "manual-tree/Testing/baseline.output"},
        ], immutable
        assert immutable["changed"] == [
            {"path": "qa/oracle.py"},
            {"path": "tests/graph2.output"},
            {"path": "tests/target_test.c"},
        ], immutable

        allowed = smell_bridge._worktree_test_change_audit(
            audit,
            allow_test_changes=True,
        )
        assert allowed["success"] is True, allowed
        assert allowed["status"] == "TEST_SOURCE_CHANGE_ALLOWED", allowed

        # The final-diff contract runs after the source Guard but before the
        # expensive project_full command. It must override the otherwise
        # independent immutable-test finding for this exact delivery defect.
        original_resolve = smell_bridge._resolve
        original_run_smell_guards = smell_bridge.run_smell_guards
        original_run_build_test_guard = smell_bridge.run_build_test_guard
        original_allow_test_changes = os.environ.get("SMELL_ALLOW_TEST_CHANGES")
        project_full_calls: list[bool] = []

        def _unexpected_project_full(*_args, **_kwargs):
            project_full_calls.append(True)
            raise AssertionError(
                "project_full must not run while final generated artifacts remain"
            )

        try:
            os.environ["SMELL_ALLOW_TEST_CHANGES"] = "1"
            smell_bridge._resolve = lambda _args: SimpleNamespace(
                project_root=root,
                language="c",
                smell="long_parameter_list",
                locations=[],
                sample_test_location="",
                verification_mode="project_full",
                build_source="fixture",
                test_source="fixture",
                profile=SimpleNamespace(retry_hint_template=""),
            )
            smell_bridge.run_smell_guards = lambda *_args, **_kwargs: []
            smell_bridge.run_build_test_guard = _unexpected_project_full
            verify = smell_bridge.cmd_verify(SimpleNamespace(
                skip_build_test=False,
                run_build_test=True,
                snapshot=True,
                baseline_seal="",
                smell_evidence="",
                artifact_root=str(Path(raw) / "verify-artifacts"),
                output_detail="decision",
            ))
        finally:
            smell_bridge._resolve = original_resolve
            smell_bridge.run_smell_guards = original_run_smell_guards
            smell_bridge.run_build_test_guard = original_run_build_test_guard
            if original_allow_test_changes is None:
                os.environ.pop("SMELL_ALLOW_TEST_CHANGES", None)
            else:
                os.environ["SMELL_ALLOW_TEST_CHANGES"] = (
                    original_allow_test_changes
                )

        assert project_full_calls == [], project_full_calls
        assert verify["success"] is False, verify
        assert verify["accepted"] is False, verify
        assert verify["status"] == "FINAL_DIFF_GENERATED_ARTIFACTS", verify
        assert verify["test_changes"]["status"] == (
            "TEST_SOURCE_CHANGE_ALLOWED"
        ), verify["test_changes"]
        verify_audit = verify["build_test_guard"][
            "final_diff_generated_artifact_audit"
        ]
        assert verify_audit["paths"] == sorted(
            (
                *generated_root_products,
                *controller_owned_products,
                *tracked_autotools_products,
                *untracked_generated_products,
            )
        ), verify_audit
        assert verify["failure_pack"]["failure_category"] == (
            "FINAL_DIFF_GENERATED_ARTIFACTS"
        ), verify["failure_pack"]
        assert verify["failure_pack"]["failure_group"] == (
            "compile"
        ), verify["failure_pack"]
        assert verify["failure_pack"]["retryable"] is True, verify[
            "failure_pack"
        ]
        recommendations = verify["failure_pack"]["recommendations"]
        restore = next(
            item
            for item in recommendations
            if item.startswith(
                "Restore tracked generated paths to the frozen baseline"
            )
        )
        remove = next(
            item
            for item in recommendations
            if item.startswith("Remove untracked generated paths")
        )
        assert "configure" in restore and "combined.o" not in restore, restore
        assert "combined.o" in remove and "configure" not in remove, remove

        # A candidate-created commit must not erase the c000-relative delivery
        # patch or hide its test edits. Commit only the deliverable paths; the
        # generated build tree remains visible and independently fail-closed.
        _run(
            root,
            "git", "add",
            "src", "tests", "qa", "spec", "Makefile", "docs",
            "src/Makefile.inc", "configure.ac", "Makefile.am",
            "CMakeLists.txt", "tools/configure", "build/real_source.c",
            "build-aux/custom-check.sh",
        )
        _run(root, "git", "commit", "-qm", "candidate commit")
        committed_snapshot = smell_bridge._snapshot_project(
            root,
            declared_test_paths=["qa/oracle.py"],
            base_commit=baseline_commit,
        )
        committed_status = committed_snapshot["status"]["stdout"]
        committed_audit = committed_snapshot["change_audit"]
        assert committed_snapshot["base_commit"] == baseline_commit
        assert committed_snapshot["diff"]["skipped_reason"] == (
            "FINAL_DIFF_GENERATED_ARTIFACTS"
        ), committed_snapshot["diff"]
        assert "src/target.c" in committed_status, committed_status
        assert "tests/target_test.c" in committed_status, committed_status
        assert "Makefile" in committed_status, committed_status
        assert committed_audit["category_counts"] == audit["category_counts"], (
            committed_audit,
            audit,
        )
        committed_immutable = smell_bridge._worktree_test_change_audit(
            committed_audit,
            allow_test_changes=False,
        )
        assert committed_immutable["status"] == "TEST_SOURCE_MODIFIED", (
            committed_immutable
        )

    print(
        "snapshot diff hygiene self-check passed: "
        "c000-relative committed/staged/unstaged patch; "
        "generated build products retained in the visible inventory; "
        "exact controller-injected paths excluded; "
        "tracked and source-owned build/test metadata retained; "
        "tracked generated build/test products fail closed; "
        "production/test/build metadata classified; "
        "immutable test edits fail closed"
    )


if __name__ == "__main__":
    main()
